title: Billy's Blog
url: https://billywhizz.io
description: "musings on 'puters"
email: apjohnsto@gmail.com

markdown: kramdown
excerpt_separator: "\n\n"

plugins: [jekyll-paginate]
permalink: /:year/:month/:day/:title/
timezone: Europe/London

paginate: 10

safe: true
lsi: false
exclude: [.gitignore, CNAME, Dockerfile, README.md]
